### PR TITLE
Update Stellar.js to v0.6.1

### PR DESCRIPTION
**Pull request by markdalgleish**
I noticed you're using a very old version of Stellar.js, so I updated it for you :)

### CODE REVIEW

**Comment by jalxob** [comment]
Thanks. I will do that change asap. :)

**Comment by markdalgleish** [comment]
You should just be able to automatically merge this via GitHub.

**Comment by jalxob** [comment]
Done!

**Comment by jalxob** [comment]
Thank you so much :)

**Comment by markdalgleish** [comment]
No worries :)

**Comment by jalxob** [comment]
Thanks?

**Pull request merged**
